// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USelection.Web.Database;

namespace USelection.Web.Migrations
{
    [DbContext(typeof(USelection2Context))]
    [Migration("20210831211312_migi1")]
    partial class migi1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("USelection.Web.Database.Exception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Poruka")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Exception");
                });

            modelBuilder.Entity("USelection.Web.Database.IzbornaJedinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("IzbornaJedinica");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "New York"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Washington"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Texas"
                        });
                });

            modelBuilder.Entity("USelection.Web.Database.IzbornaJedinicaKandidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrojOsvojenihGlasova")
                        .HasColumnType("int");

                    b.Property<int?>("IzbornaJedinicaId")
                        .HasColumnType("int")
                        .HasColumnName("IzbornaJedinicaID");

                    b.Property<int?>("KandidatId")
                        .HasColumnType("int")
                        .HasColumnName("KandidatID");

                    b.Property<bool?>("OverrideFile")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IzbornaJedinicaId");

                    b.HasIndex("KandidatId");

                    b.ToTable("IzbornaJedinicaKandidat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojOsvojenihGlasova = 1233,
                            IzbornaJedinicaId = 1,
                            KandidatId = 1,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 2,
                            BrojOsvojenihGlasova = 733,
                            IzbornaJedinicaId = 1,
                            KandidatId = 2,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 3,
                            BrojOsvojenihGlasova = 1003,
                            IzbornaJedinicaId = 1,
                            KandidatId = 3,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 4,
                            BrojOsvojenihGlasova = 1033,
                            IzbornaJedinicaId = 2,
                            KandidatId = 1,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 5,
                            BrojOsvojenihGlasova = 1733,
                            IzbornaJedinicaId = 2,
                            KandidatId = 2,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 6,
                            BrojOsvojenihGlasova = 903,
                            IzbornaJedinicaId = 2,
                            KandidatId = 3,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 7,
                            BrojOsvojenihGlasova = 533,
                            IzbornaJedinicaId = 3,
                            KandidatId = 1,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 8,
                            BrojOsvojenihGlasova = 733,
                            IzbornaJedinicaId = 3,
                            KandidatId = 2,
                            OverrideFile = false
                        },
                        new
                        {
                            Id = 9,
                            BrojOsvojenihGlasova = 700,
                            IzbornaJedinicaId = 3,
                            KandidatId = 3,
                            OverrideFile = false
                        });
                });

            modelBuilder.Entity("USelection.Web.Database.Kandidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeIprezime")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ImeIPrezime");

                    b.Property<string>("SifraKandidata")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Kandidat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImeIprezime = "Donald Trump",
                            SifraKandidata = "DT"
                        },
                        new
                        {
                            Id = 2,
                            ImeIprezime = "Hillary Clinton",
                            SifraKandidata = "HC"
                        },
                        new
                        {
                            Id = 3,
                            ImeIprezime = "Joe Biden",
                            SifraKandidata = "JB"
                        });
                });

            modelBuilder.Entity("USelection.Web.Database.IzbornaJedinicaKandidat", b =>
                {
                    b.HasOne("USelection.Web.Database.IzbornaJedinica", "IzbornaJedinica")
                        .WithMany("IzbornaJedinicaKandidats")
                        .HasForeignKey("IzbornaJedinicaId")
                        .HasConstraintName("FK__IzbornaJe__Izbor__2A4B4B5E");

                    b.HasOne("USelection.Web.Database.Kandidat", "Kandidat")
                        .WithMany("IzbornaJedinicaKandidats")
                        .HasForeignKey("KandidatId")
                        .HasConstraintName("FK__IzbornaJe__Kandi__2B3F6F97");

                    b.Navigation("IzbornaJedinica");

                    b.Navigation("Kandidat");
                });

            modelBuilder.Entity("USelection.Web.Database.IzbornaJedinica", b =>
                {
                    b.Navigation("IzbornaJedinicaKandidats");
                });

            modelBuilder.Entity("USelection.Web.Database.Kandidat", b =>
                {
                    b.Navigation("IzbornaJedinicaKandidats");
                });
#pragma warning restore 612, 618
        }
    }
}
